package:
  name: p2
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'notag') }}

source:
  git_url: ../

build:
  string: {{ environ.get('GIT_DESCRIBE_NUMBER','0') + "_jeh" }}

requirements:
  build:
    - python

  run:
    - python

